<<<<<<< HEAD
services:
  - type: web
    name: lshay-loan-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt && python train_models.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
=======
services:
  - type: web
    name: lshay-loan-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt && python train_models.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
>>>>>>> 9f0dc4fbe2558693855a50fc425a4f1978d581a7
